/**
 * ORTHOGONAL - ENG · PIPING DESIGN & ISOMETRICS (PD&I)
 * COPYRIGHT (C) 2026 ORTHOGONAL - ENG. ALL RIGHTS RESERVED.
 * PROPRIETARY INDUSTRIAL PIPING CAD & ISOMETRIC ENGINE.
 * UNAUTHORIZED COPYING, REVERSE ENGINEERING OR DISTRIBUTION IS STRICTLY PROHIBITED.
 */

export const PDI_ENGINE_IDENTITY = {
  vendor: "ORTHOGONAL - ENG",
  product: "Piping Design & Isometrics (PD&I)",
  version: "4.8d",
  revision: "2026.09-PRO",
  copyright: "© 2026 ORTHOGONAL - ENG. All rights reserved.",
  licenseTerms: "Commercial Enterprise & Engineering Software License",
  supportContact: "contact@orthogonal-eng.com",
} as const;

export const PDI_WATERMARK_SIGNATURE = "POWERED_BY_ORTHOGONAL_ENG_2026";

/**
 * Signe un objet de données projet avant export ou sauvegarde locale
 */
export function pdiSignExportData<T extends Record<string, any>>(data: T): T & {
  _orthogonalEngSignature: {
    vendor: string;
    engine: string;
    watermark: string;
    timestamp: string;
    integrityHash: string;
  };
} {
  const timestamp = new Date().toISOString();
  // Simple deterministic integrity stamp
  const stamp = `${PDI_WATERMARK_SIGNATURE}::${timestamp}::${JSON.stringify(data).length}`;
  let hash = 0;
  for (let i = 0; i < stamp.length; i++) {
    hash = (hash << 5) - hash + stamp.charCodeAt(i);
    hash |= 0;
  }

  return {
    ...data,
    _orthogonalEngSignature: {
      vendor: PDI_ENGINE_IDENTITY.vendor,
      engine: `${PDI_ENGINE_IDENTITY.product} v${PDI_ENGINE_IDENTITY.version}`,
      watermark: "Powered by ORTHOGONAL - ENG",
      timestamp,
      integrityHash: `OE-${Math.abs(hash).toString(16).toUpperCase()}`,
    },
  };
}

/**
 * Génère le bloc textuel normalisé pour les métadonnées PDF / DXF
 */
export function pdiGetEngineeringStamp(title?: string, docNum?: string): string {
  return [
    `GENERATED BY ${PDI_ENGINE_IDENTITY.product.toUpperCase()}`,
    `ENGINEERING SUITE · POWERED BY ${PDI_ENGINE_IDENTITY.vendor}`,
    title ? `DOCUMENT: ${title}` : "",
    docNum ? `REF: ${docNum}` : "",
    PDI_ENGINE_IDENTITY.copyright,
  ]
    .filter(Boolean)
    .join(" | ");
}
